version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "dbdata:/var/lib/mysql/FormSite"
  web:
    image: formsite
    build: ./
    ports:
      - "8080:8080"

volumes:
  dbdata:
      